### PR TITLE
for folks that do not use redis to cache to disk

### PR DESCRIPTION
**Pull request by codylane**
This pull requests addresses a possible use case (at least for my team) that doesn't use redis to cache to disk.  I'm hoping that this can be merged to master where it's a noop for anyone that doesn't use redis the way my team does, but gives my team the ability to not cache to disk.  

Please let me know if i've missed anything.  I appreciate your time and feedback.

### CODE REVIEW

**Comment by petems** [comment]
LGTM, when Travis goes green I'll merge! 👍

**Comment by codylane** [comment]
You rock dude, thank you so much.

**Comment by codylane** [comment]
Well, that failure is interesting, I cannot duplicate this on my workstation.  I've spent an hour now trying to understand what is going on with the single failing test and I'm seriously scratching my head.

@petems - I know you are working on this too.  Do you have any ideas?

**Comment by codylane** [comment]
Thinking about this deeper, this feels more like a ruby bug.  Let me see if I can find a bug report about this.

**Comment by petems** [comment]
I believe it's actually an issue with how undef is represented in older Puppet

**Comment by codylane** [comment]
Ahh, that also makes sense.  Can you help me understand which version of puppet is being installed in travis for that failing test?  I apologize if this is easy to find and I'm overlooking it.

**Comment by petems** [comment]
I think it should be fixed in this, it's weird issues with how `scope[` works with `undef` values

**Comment by codylane** [comment]
Ugh, so we have to go through all the templates and add the following to test for undef?  Would you like me to do that?  I have no problem doing so.

```
unless [:undef, false, nil, ''].include?(scope['somevar'])
```

**Comment by codylane** [comment]
I wish we could just use this but I can see how it could be problematic for folks as I've seen some people quote booleans, or quote undef... etc.

```
<% unless scope['somevar'].nil? -%>
# do something when variable is defined
<% else -%>
# do something else when variable is not defined
<% end -%>
```

**Pull request closed without merging**
