### PR TITLE
Multi instances

### PR DESCRIPTION
**Pull request by spo0nman**
Fixed the errors travis complained about.

### CODE REVIEW

**Comment by bostrowski13** [comment]
It'd be very nice to have this multi instance features.  Is anybody working on this or any timeframe for getting this into master?

**Comment by spo0nman** [comment]
Hi, I worked on this, but i was not able to get a proper test environment running to merge this back. I would have some time again in Feb to give it another try.

**Comment by jacobmw** [comment]
I am trying to use this new feature from your fork but seem to be missing something.  I'm not quite sure how to pass the hash expected for the instances parameter.  You code says it is expecting a hash, should it be an array of hashes?  Could you show me an example of how to use multiple instances?  Assuming I can get this to work I may be able to help write some tests.

**Comment by spo0nman** [comment]
@jacobmw the issue tracking this has an example: https://github.com/arioch/puppet-redis/issues/113

**Comment by v6** [comment]
// , Can you rebase this on top of master to resolve the conflicts, or is that something for one of the core contributors to do?

**Comment by spo0nman** [comment]
@v6 Some of the tests failed with my branch, I do not have a working test environment to test these. 
I will try to rebase this on master and create a new branch, are you are interested in helping me with the travis tests?

**Comment by bostrowski13** [comment]
is there a place to pull the latest of this feature?  is there anything i can do to help move this forward?

**Comment by petems** [comment]
@bostrowski13 I'm still working on the bulk of the work for multi-instances on one server, I should have some slack time over the weekend where I can help implement this.

Can you give me your requirements on what you're looking for in the feature?

**Comment by bostrowski13** [comment]
really looking for hosting multiple instances across a redis sentinel cluster.  we have an older version of redis which hosts 5 different instances hosted on different ports.  most have the same config, but would like the option of shared config options with per-instance config, if necessary.

**Comment by petems** [comment]
@bostrowski13 is this all on the same machine? Because it's possible to configure multi-redis with sentinel on many machines right now with the module?

**Comment by petems** [comment]
Closing this in favour of #200, lots of rebasing on this PR and should have an MVP of multi-redis instances on one server.

@spo0nman Thanks for your PR, I ended up taking a lot of the work for my implementation. If there's anything I've missed or comments, feel free to comment on #200! 😄

**Pull request closed without merging**
