### PR TITLE
Add an optional third parameter to redisget() to specify a default value

### PR DESCRIPTION
**Pull request by petems**
Rebase of #207 with docs

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Thanks! In accordance with SemVer, could you please release a new version of this module? This contribution would move us from 3.0.0 to 3.1.0.

**Comment by petems** [comment]
Yep yep, will do! 👍

**Comment by ghoneycutt** [comment]
Thank you. Could you please post the release here, so I'm notified.

**Comment by petems** [comment]
Can do, we're trying to get the auto-release stuff working so it's automatic in the future also 👍

**Comment by arioch** [comment]
@ghoneycutt: as requested.
The auto-release failed, manually uploaded to the forge in the meantime.

**Pull request merged**
