### PR TITLE
Redis 3 Cluster

### PR DESCRIPTION
**Pull request by claudio-walser**
Implemented redis 3.0 cluster functionality

### CODE REVIEW

**Comment by arioch** [comment]
Looking good so far. :+1:
However could you squash this patch in a single commit?
If possible some unit testing would be greatly appreciated.

**Comment by claudio-walser** [comment]
Sure, i'll have a look and come back to you later...

**Comment by claudio-walser** [comment]
Ok i messed it up now, ill probably going to close this one, fix everything you requested and then open e new pull request...

Sorry for that

**Comment by arioch** [comment]
Not to worry, you can just force push into this PR. :smile:

**Pull request closed without merging**
