### PR TITLE
Add systemd support for sentinel service

### PR DESCRIPTION
**Pull request by petems**
Rebased of #176 with some spec fixes

### CODE REVIEW

**Comment by petems** [comment]
@KlavsKlavsen Ok, so this seems to work for Ubuntu, but the service file for redis breaks on CentOS (as the acceptance tests show)

The default service file in CentOS looks like this:

```
[Unit]
Description=Redis Sentinel
After=network.target

[Service]
ExecStart=/usr/bin/redis-sentinel /etc/redis-sentinel.conf --daemonize no
ExecStop=/usr/bin/redis-shutdown redis-sentinel
User=redis
Group=redis

[Install]
WantedBy=multi-user.target
```

This works with no issues, so there's something in the new config that causes issues.

I put logic around the `/bin/run-parts` because they're Debian-flavour only, but still having issues.

**Comment by KlavsKlavsen** [comment]
its already odd that you want to control the service/init scripts for redis-sentinel - and NOT for redis.. :)
I assume its a legacy from when there was no "redis-sentinel" service - and you wanted to support that ?
we'd need a centos version in the patch and select based on os.

**Comment by petems** [comment]
Yeah, the packages for Ubuntu 14.04 and Debian stable don't have the redis-sentinel package. This module dates back to 2014, so there's some stuff in here that's probably not as relevant now. 

I'm just double checking from your issue before, are you using the ppa for redis or the standard xenial repo?

**Comment by KlavsKlavsen** [comment]
standard xenial repo..

**Comment by petems** [comment]
We might want to manage this in the future but for now I think we're ok leaving this, as the original location of the config file was fixed in #184  so closing

**Pull request closed without merging**
