### PR TITLE
Marc/redis server and sentinel both running or not

### PR DESCRIPTION
**Pull request by marcgascon**
The idea to solve the issue is something like that. I have to test it but I've created the PR @arioch just in case anyone wants to participate on it.

### CODE REVIEW

**Comment by marcgascon** [comment]
Now I've tested on debian and it's working properly. I'm not so proud of the if statements on init.pp so if you have any idea of how to structure it, it will be more than welcome, but the issue is solved with that.

Hope to recive some feedback soon.

Thanks in advance.

**Comment by arioch** [comment]
My apologies for the late response...

Looks good though.
Could you rebase that onto the latest commit?

**Comment by marcgascon** [comment]
Thanks @arioch now branch is rebased. You are able to merge it, but if you can take another look before, that would be great!

Thanks!

**Comment by petems** [comment]
@marcgascon There's been a few merges with this one, can you re-open with a rebase if still needed?

**Pull request closed without merging**
