### PR TITLE
Added more configuration options to redis.conf

### PR DESCRIPTION
**Pull request by hanej**
I added the following configuration options to redis.conf and set the default values to the default values from Redis.

- aof_load_truncated
- aof_rewrite_incremental_fsync
- appendfilename
- hll_sparse_max_bytes
- latency_monitor_threshold
- min_slaves_max_lag
- min_slaves_to_write
- notify_keyspace_events
- repl_backlog_size
- repl_backlog_ttl
- repl_disable_tcp_nodelay
- slave_priority
- tcp_backlog

### CODE REVIEW

**Comment by hanej** [comment]
Is there anything else you need to merge this in?

**Comment by arioch** [comment]
Caffeine. Lots of caffeine. :coffee: 
All kidding aside I'll try to find some time tomorrow to review and merge this PR.

**Comment by hanej** [comment]
I know the feeling.  Thanks, man!  I appreciate it.

**Comment by arioch** [comment]
Finally got around to it.
Looking good, thanks!

**Pull request merged**
