### PR TITLE
Add redis::instance defined type

### PR DESCRIPTION
**Pull request by petems**
This will allow configuring multiple redis instances on one machine, allowing the first step towards #113

### CODE REVIEW

**Comment by petems** [comment]
@jacobmw @v6 @spo0nman @bostrowski13

Working MVP of two redis instances on one server, running on two different ports:

```puppet
class { '::redis':
      manage_repo     => #{manage_repo},
      default_install => false,
    }

    redis::instance_config {'redis1':
      port     => '7777',
      pid_file => '/var/run/redis/redis-server-redis1.pid'
    } ~> redis::instance_service {'redis1':}

    redis::instance_config {'redis2':
      port     => '8888',
      pid_file => '/var/run/redis/redis-server-redis2.pid'
    } ~> redis::instance_service {'redis2':}
```

Does this fit people's needs? I'm planning on merging the instance_config and instance_service into one to make this a bit easier to use 😄

**Comment by bostrowski13** [comment]
this work sfor me.  are other params defined within each instance like you specified the pid_file?

**Comment by petems** [comment]
@bostrowski13 Yep, all of the parameters defined are the same that would be the defined the main class. In fact, you no longer need to specify the pid, you can just do:

```
class { '::redis':
      default_install => false,
    }

    redis::instance {'redis1':
      port     => '7777',
    }

    redis::instance {'redis2':
      port     => '8888',
    }
```

**Comment by bostrowski13** [comment]
that is excellent.  thank you!

**Comment by spo0nman** [comment]
@petems good to know that this code is getting used. In my earlier PR there was a bug where the data directory for redis was shared between the instances, I fixed it in my fork but never published. Look out for this bug. Good luck!

**Comment by petems** [comment]
@spo0nman Ooh, interesting, that's a good point actually. I should probably add a test to make sure each instance uses it's own data folder

But yes, your original code was instrumental in getting this working so thank you very much! 😄

**Comment by tdotgreenshirt** [comment]
What about having separate sentinel instances? Is it possible to do this or can sentinel monitor multiple Redis instances without creating a separate sentinel instance for each.

**Comment by petems** [comment]
@tdotgreenshirt From my understanding, you don't want the sentinel instance on the same machine as the redis instance because it would be a SPOF: When you lose that host you lose both.

If there is a case for multi-sentinal on one host, then it could be added as a feature?

**Comment by tdotgreenshirt** [comment]
@petems This is similar to what we are doing:
https://i.stack.imgur.com/Citcm.png

However, if we have separate Redis instances, we also need a separate Sentinel instances.

**Comment by petems** [comment]
@tdotgreenshirt Ok, can you add that as an issue and I'll tag it as an upcoming feature.

Now we have a defined instance type, and redis-sentinel is just another redis instance, this should be fairly quick to implement 😄

**Comment by bostrowski13** [comment]
thats actually very similar as to what we're after as well.  be great to have that option for sentinel.

**Comment by tdotgreenshirt** [comment]
Created issue for multiple Sentinel instances: https://github.com/arioch/puppet-redis/issues/223

**Pull request merged**
