### PR TITLE
Redis Cluster 3.0 Feature

### PR DESCRIPTION
**Pull request by claudio-walser**
Got it properly now :)

### CODE REVIEW

**Comment by arioch** [comment]
Excellent!
I guess you'll be making some people happy with this patch.

Bonus points for docs and unit tests! :+1:

**Comment by v6** [comment]
:+1: You sure made me happy. 

I also figured out how to install this early: 

http://stackoverflow.com/questions/34035364/how-do-i-build-and-install-a-puppet-module-locally-from-source

**Comment by arioch** [comment]
In the past 6 years dealing with Puppet I've never used Forge to install modules myself.
Anyways for people who do it that way I proved builds. I've just cut a new release: https://forge.puppetlabs.com/arioch/redis/1.2.0/readme.

Enjoy. ;)

**Comment by v6** [comment]
// , Thanks, @arioch.

**Pull request merged**
